<?php
/**
 * Plugin Name: Plugin Activation Manager
 * Description: Auto-generated by sitchco/wp-composer-automator. Enforces per-environment plugin activation rules.
 *
 * This file is auto-generated. Do not edit directly.
 * To modify rules, update the "plugin-activation" key in your root composer.json under "extra",
 * then re-run `composer install` or `composer dump-autoload`.
 */

if (! defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

$rules = /* __RULES_PLACEHOLDER__ */ [];
$transientKey = 'plugin_activation_bypass';

add_action('admin_init', function () use ($rules, $transientKey) {
    if (is_multisite() || ! defined('WP_ENVIRONMENT_TYPE') || empty($rules) || get_transient($transientKey)) {
        return;
    }

    // Only converge plugin state on an interactive wp-admin request. admin_init
    // also fires on background requests (notably admin-ajax.php), where another
    // plugin may be filtering `option_active_plugins` — e.g. WP Migrate's
    // compatibility mode reduces it to itself during a migration. Because
    // activate_plugin()/deactivate_plugins() read that filtered list via
    // get_option() and write it straight back, enforcing here would silently
    // deactivate every other plugin. Enforcement is opportunistic and only needs
    // a real admin page load, so skip every non-interactive context.
    if (
        wp_doing_ajax()
        || wp_doing_cron()
        || (defined('REST_REQUEST') && REST_REQUEST)
        || (defined('WP_CLI') && WP_CLI)
        || (defined('XMLRPC_REQUEST') && XMLRPC_REQUEST)
    ) {
        return;
    }

    $environment = wp_get_environment_type();

    if (! function_exists('get_plugins')) {
        require_once ABSPATH . 'wp-admin/includes/plugin.php';
    }

    $basenames = array_keys(get_plugins());
    $directoryMap = array_combine(array_map(dirname(...), $basenames), $basenames);
    unset($directoryMap['.']);

    foreach ($rules as $directory => $envRules) {
        if (! isset($directoryMap[$directory])) {
            continue;
        }

        $basename = $directoryMap[$directory];

        $rule = $envRules[$environment] ?? $envRules['*'] ?? null;
        if ($rule === null) {
            continue;
        }

        if ($rule === true && ! is_plugin_active($basename)) {
            activate_plugin($basename);
        } elseif ($rule === false && is_plugin_active($basename)) {
            deactivate_plugins($basename);
        }
    }
});

$bypassCallback = function ($basename) use ($rules, $transientKey) {
    $directory = dirname($basename);
    if ($directory === '.' || ! isset($rules[$directory])) {
        return;
    }
    set_transient($transientKey, 1, HOUR_IN_SECONDS);
};

add_action('activated_plugin', $bypassCallback);
add_action('deactivated_plugin', $bypassCallback);
